var formbuilder_langs = {
    newSection: "セクションを新規",
    divName: "セクション名",
    column1: "1カラム",
    column2: "2カラム",
    column3: "3カラム",
    delete: "削除",
    ja: "日本語",
    en: "英語",
    vi: "ベトナム語",
    fieldProperties: 'フィールドのオプション',
    static: '一段階層',
    dynamic: '複数階層',
    addOption: 'オプションを追加',
    allFieldsRemoved: 'すべてのフィールドが削除されました。',
    allowSelect: 'セレクトを許可する',
    allowMultipleFiles: 'Allow users to upload multiple files',
    autocomplete: 'オートコンプリート',
    button: 'ボタン',
    cannotBeEmpty: 'このフィールドの内容が必要です。',
    pleaseEnterData: '必要なフィールドを入力してください。',
    checkboxGroup: 'チェックボックスグループ',
    checkbox: 'チェックボックス',
    checkboxes: 'チェックボックス',
    className: 'クラス',
    widthNotSet: 'なし',
    clearAllMessage: '全てクエリしてもよろしですか？',
    clearAll: 'クリア',
    close: '戻る',
    content: '内容',
    copy: 'クリップボードにコピーする',
    copyButton: '&#43;',
    copyButtonTooltip: 'コピー',
    dateField: '日付フィールド',
    description: '説明',
    descriptionField: '説明フィールド',
    devMode: 'Developer Mode',
    editNames: '名前を編集する',
    editorTitle: 'フォーム要素',
    editXML: 'XMLを編集する',
    enableOther: 'Enable &quot;Other&quot;',
    enableOtherMsg: 'Let users to enter an unlisted option',
    fieldDeleteWarning: false,
    fieldVars: 'フィールド変数',
    fieldNonEditable: 'このフィールドは変更禁止です。',
    fieldRemoveWarning: 'このフィールドを削除してもよろしいですか？',
    fileUpload: 'File Upload',
    formUpdated: 'Form Updated',
    getStarted: 'Drag a field from the right to this area',
    header: 'ヘッダ',
    hide: '編集',
    hidden: 'Hidden Input',
    label: 'ラベル',
    labelEmpty: '必須項目です。',
    limitRole: 'Limit access to one or more of the following roles:',
    mandatory: 'Mandatory',
    maxlength: '最大文字数',
    minOptionMessage: 'This field requires a minimum of 2 options',
    multipleFiles: '複数ファイル',
    name: '名前',
    no: 'いいえ',
    number: '数字',
    off: 'Off',
    on: 'On',
    option: 'オプション',
    optional: 'optional',
    optionLabelPlaceholder: 'ラベル',
    optionValuePlaceholder: '値',
    optionEmpty: '必須',
    other: 'Other',
    paragraph: 'パラグラフ',
    placeholder: 'プレースホルダー',
    placeholders: {
        value: '値',
        label: 'ラベル',
        text: '',
        textarea: '',
        email: 'メールアドレスを入力してください。',
        placeholder: '',
        className: 'space separated classes',
        password: 'パスワードを入力してください。'
    },
    preview: 'Preview',
    radioGroup: 'ラジオグループ',
    radio: 'ラジオ',
    removeMessage: '削除',
    remove: '&#215;',
    required: '必要',
    richText: 'Rich Text Editor',
    roles: 'Access',
    save: '保存',
    selectOptions: 'オプション',
    select: 'セレクト',
    selectColor: '色をセレクト',
    selectionsMessage: '複数選択を許可します',
    size: 'サイズ',
    sizes: {
        xs: '最小',
        sm: '小',
        m: 'デフォルト',
        lg: '大'
    },
    style: 'スタイル',
    styles: {
        btn: {
            'default': 'デフォルト',
            danger: 'Danger',
            info: 'Info',
            primary: 'Primary',
            success: 'Success',
            warning: 'Warning'
        }
    },
    subtype: 'タイプ',
    subtypes: {
        text: ['text', 'password', 'email', 'color', 'tel'],
        button: ['button', 'submit'],
        header: ['h1', 'h2', 'h3'],
        paragraph: ['p', 'address', 'blockquote', 'canvas', 'output']
    },
    text: 'テキストフィールド',
    textArea: 'テキストエリア',
    toggle: 'トグル',
    warning: '警告!',
    value: '値',
    viewJSON: '{  }',
    viewXML: '&lt;/&gt;',
    yes: 'はい'
};