/*!
* phone-codes/phone-ja.js
*/

!function(factory) {
    "function" == typeof define && define.amd ? define([ "../inputmask" ], factory) : "object" == typeof exports ? module.exports = factory(require("../inputmask")) : factory(window.Inputmask);
}(function(Inputmask) {
    return Inputmask.extendAliases({
        phoneja: {
            alias: "abstractphone",
            countrycode: "81",
            phoneCodes: [
                {mask: '018-####-####', cc: 'JP', cd: 'Japan', city: 'Akita'},
                {mask: '06-####-####', cc: 'JP', cd: 'Japan', city: 'Amagasaki'},
                {mask: '0166-####-####', cc: 'JP', cd: 'Japan', city: 'Asahikawa'},
                {mask: '043-####-####', cc: 'JP', cd: 'Japan', city: 'Chiba'},
                {mask: '0466-####-####', cc: 'JP', cd: 'Japan', city: 'Fujisawa'},
                {mask: '092-####-####', cc: 'JP', cd: 'Japan', city: 'Fukuoka'},
                {mask: '084-####-####', cc: 'JP', cd: 'Japan', city: 'Fukuyama'},
                {mask: '047-####-####', cc: 'JP', cd: 'Japan', city: 'Funabashi'},
                {mask: '058-####-####', cc: 'JP', cd: 'Japan', city: 'Gifu'},
                {mask: '042-####-####', cc: 'JP', cd: 'Japan', city: 'Hachioji'},
                {mask: '053-####-####', cc: 'JP', cd: 'Japan', city: 'Hamamatsu'},
                {mask: '06-####-####', cc: 'JP', cd: 'Japan', city: 'Higashiosaka'},
                {mask: '079-####-####', cc: 'JP', cd: 'Japan', city: 'Himeji'},
                {mask: '072-####-####', cc: 'JP', cd: 'Japan', city: 'Hirakata'},
                {mask: '082-####-####', cc: 'JP', cd: 'Japan', city: 'Hiroshima'},
                {mask: '047-####-####', cc: 'JP', cd: 'Japan', city: 'Ichikawa'},
                {mask: '0586-####-####', cc: 'JP', cd: 'Japan', city: 'Ichinomiya'},
                {mask: '0246-####-####', cc: 'JP', cd: 'Japan', city: 'Iwaki'},
                {mask: '099-####-####', cc: 'JP', cd: 'Japan', city: 'Kagoshima'},
                {mask: '076-####-####', cc: 'JP', cd: 'Japan', city: 'Kanazawa'},
                {mask: '04-####-####', cc: 'JP', cd: 'Japan', city: 'Kashiwa'},
                {mask: '0568-####-####', cc: 'JP', cd: 'Japan', city: 'Kasugai'},
                {mask: '049-####-####', cc: 'JP', cd: 'Japan', city: 'Kawagoe'},
                {mask: '048-####-####', cc: 'JP', cd: 'Japan', city: 'Kawaguchi'},
                {mask: '044-####-####', cc: 'JP', cd: 'Japan', city: 'Kawasaki'},
                {mask: '093-####-####', cc: 'JP', cd: 'Japan', city: 'Kitakyushu'},
                {mask: '078-####-####', cc: 'JP', cd: 'Japan', city: 'Kobe'},
                {mask: '088-####-####', cc: 'JP', cd: 'Japan', city: 'Kochi'},
                {mask: '055-####-####', cc: 'JP', cd: 'Japan', city: 'Kofu'},
                {mask: '024-####-####', cc: 'JP', cd: 'Japan', city: 'Koriyama'},
                {mask: '096-####-####', cc: 'JP', cd: 'Japan', city: 'Kumamoto'},
                {mask: '048-####-####', cc: 'JP', cd: 'Japan', city: 'Koshigaya'},
                {mask: '086-####-####', cc: 'JP', cd: 'Japan', city: 'Kurashiki'},
                {mask: '075-####-####', cc: 'JP', cd: 'Japan', city: 'Kyoto'},
                {mask: '042-####-####', cc: 'JP', cd: 'Japan', city: 'Machida'},
                {mask: '027-####-####', cc: 'JP', cd: 'Japan', city: 'Maebashi'},
                {mask: '047-####-####', cc: 'JP', cd: 'Japan', city: 'Matsudo'},
                {mask: '089-####-####', cc: 'JP', cd: 'Japan', city: 'Matsuyama'},
                {mask: '0985-####-####', cc: 'JP', cd: 'Japan', city: 'Miyazaki'},
                {mask: '026-####-####', cc: 'JP', cd: 'Japan', city: 'Nagano'},
                {mask: '095-####-####', cc: 'JP', cd: 'Japan', city: 'Nagasaki'},
                {mask: '052-####-####', cc: 'JP', cd: 'Japan', city: 'Nagoya'},
                {mask: '098-####-####', cc: 'JP', cd: 'Japan', city: 'Naha'},
                {mask: '0742-####-####', cc: 'JP', cd: 'Japan', city: 'Nara'},
                {mask: '025-####-####', cc: 'JP', cd: 'Japan', city: 'Niigata'},
                {mask: '0798-####-####', cc: 'JP', cd: 'Japan', city: 'Nishinomiya'},
                {mask: '097-####-####', cc: 'JP', cd: 'Japan', city: 'Oita'},
                {mask: '086-####-####', cc: 'JP', cd: 'Japan', city: 'Okayama'},
                {mask: '0564-####-####', cc: 'JP', cd: 'Japan', city: 'Okazaki'},
                {mask: '06-####-####', cc: 'JP', cd: 'Japan', city: 'Osaka'},
                {mask: '077-####-####', cc: 'JP', cd: 'Japan', city: 'Otsu'},
                {mask: '042-####-####', cc: 'JP', cd: 'Japan', city: 'Sagamihara'},
                {mask: '048-####-####', cc: 'JP', cd: 'Japan', city: 'Saitama'},
                {mask: '072-####-####', cc: 'JP', cd: 'Japan', city: 'Sakai'},
                {mask: '011-####-####', cc: 'JP', cd: 'Japan', city: 'Sapporo'},
                {mask: '022-####-####', cc: 'JP', cd: 'Japan', city: 'Sendai'},
                {mask: '054-####-####', cc: 'JP', cd: 'Japan', city: 'Shizuoka'},
                {mask: '06-####-####', cc: 'JP', cd: 'Japan', city: 'Suita'},
                {mask: '087-####-####', cc: 'JP', cd: 'Japan', city: 'Takamatsu'},
                {mask: '027-####-####', cc: 'JP', cd: 'Japan', city: 'Takasaki'},
                {mask: '072-####-####', cc: 'JP', cd: 'Japan', city: 'Takatsuki'},
                {mask: '04-####-####', cc: 'JP', cd: 'Japan', city: 'Tokorozawa'},
                {mask: '03-####-####', cc: 'JP', cd: 'Japan', city: 'Tokyo'},
                {mask: '076-####-####', cc: 'JP', cd: 'Japan', city: 'Toyama'},
                {mask: '0532-####-####', cc: 'JP', cd: 'Japan', city: 'Toyohashi'},
                {mask: '06-####-####', cc: 'JP', cd: 'Japan', city: 'Toyonaka'},
                {mask: '0565-####-####', cc: 'JP', cd: 'Japan', city: 'Toyota'},
                {mask: '028-####-####', cc: 'JP', cd: 'Japan', city: 'Utsunomiya'},
                {mask: '073-####-####', cc: 'JP', cd: 'Japan', city: 'Wakayama'},
                {mask: '059-####-####', cc: 'JP', cd: 'Japan', city: 'Yokkaichi'},
                {mask: '045-####-####', cc: 'JP', cd: 'Japan', city: 'Yokohama'},
                {mask: '046-####-####', cc: 'JP', cd: 'Japan', city: 'Yokosuka'},
                
                // Mobile phone
                {mask: '070-####-####', cc: 'JP', cd: 'Japan', city: 'Mobile'},
                {mask: '080-####-####', cc: 'JP', cd: 'Japan', city: 'Mobile'},
                {mask: '090-####-####', cc: 'JP', cd: 'Japan', city: 'Mobile'},
            ]
        }
    }), Inputmask;
});